### ISSUE TITLE
Bug with validating Auth code

### ISSUE THREAD

**Issue by olelis** [paytrail/e2-module#18]
Currently, there is a problem with validating authentication code function.

Specifically, bug is here: 
`\Paytrail\E2Module\Validator::returnAuthcodeIsValid` or here:
`\Paytrail\E2Module\Authcode::calculateReturnAuthCode`

This bug occurs when if you have GET with fields that are not part of a signature.
For example:
`?target=paysuccess&ORDER_NUMBER=20200813201274&PAY....
`

Problem occurs because signature function takes all GET fields in the account, however, when RETURN_AUTHCODE is calculated on the Paytrail servers, only part of the fields are taken into account

**Steps to Reproduce**

1. Create new test payment with extra  get fields in the url 
2. complete test payment
3. it is failed

**Expected behaviour**

Even when you specify whole $_GET as signature validation, function should only check fields needed for signature.

**Linked bugs**
When, for some reason, order of the fields in the GET will be different, then signature will fail also.

**Additional context**
There are also errors on the tests and in the documentation.
https://docs.paytrail.com/payments/e2-interface/return-authcode/
Documentation says that only 5+1 fields are used.
However, actually, following fields are used, in this exact order:
`ORDER_NUMBER,PAYMENT_ID,AMOUNT,CURRENCY,PAYMENT_METHOD,TIMESTAMP,STATUS`

Also, ValidatorTest.php should include test for this kind of behaviour.

**Existing workaround**
Only specify needed fields for the `returnAuthcodeIsValid` method. 

Example:

        $keys = explode(',', 'ORDER_NUMBER,PAYMENT_ID,AMOUNT,CURRENCY,PAYMENT_METHOD,TIMESTAMP,STATUS,RETURN_AUTHCODE');

        $signature = [];
        foreach ($keys as $key) {
            $signature[$key] = $_GET[$key] ?? null;
        }

        if (!$e2Payment->returnAuthcodeIsValid($signature) || !$e2Payment->isPaid($_GET)) {
            // not paid
        }

However, this method contradicts documentation: 
`$isValidPayment = $e2Payment->returnAuthcodeIsValid($_GET);`
will return false.

**Comment by olelis** [comment]
Not sure why it is added as "question", because it should be "bug".

**Comment by Jipsukka** [comment]
@olelis Reason why it's labeled as `question` and not `bug`, is that we always want to determinate each time if it's really a bug in library, bug in Paytrail system, or intended functionally, as well as determine initial priority. Also testing possible bug properly might lead finding underlying issues, and helps to prioritize fixing issue better.
This gives also possibility to rethink intended functionally and rather label them as feature requests, rather than bug.

In this case it was clearly high priority bug and will be fixed as soon as PR gets reviewed and new release will be made.

**Comment by Jipsukka** [comment]
@olelis This issue has been fixed in 1.1.2 release.
